name: Build and Deploy Prod
on:
  push:
    branches:
      - master
    tags:
      - v0.*
jobs:
  build-and-deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Build 🔧
        run: |
          npm install
          npx gulp build-prod

      - name: Deploy 🚀
        if: ${{ github.ref_type == 'tag' }}
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: dist # The branch the action should deploy to.
          folder: releases # The folder the action should deploy.
          clean: false # build is already clean (keep prod/dev)
